public with sharing class CaseAppLiterals {
	public static final String CONSUMED_SLA = 'ConsumedSLA';
    public static final String TEAMNAME = 'TeamName';
    public static final String ASSIGNEDSLA = 'AssignedSLA';
    public static final String SLAMET = 'SLAMet';
    public static final String DAYS = 'days';
     public static final String MET = 'Met';
    public static final String NOTMET = 'Not Met';
    public static final String QUEUE = 'Queue';
    public static final String CLOSED = 'Closed';
    public static final String USER_STARTCODE = '005';
    public static final String SPACE = ' ';
    public static final String DAY = 'day';
    public static final String HOURS = 'hours';
    public static final String MINUTES = 'minutes';
    public static final String INPROGRESS = 'In Progress';
    public static final String NEWSTATUS = 'New';
    public static final string ORTHOFIBUSINESSHOURS = 'OrthoFiSuccess Business Hours';
    public static final Integer USERSLA = 5;
    
}